kind: pipeline
name: phb-bot

# Definir o passo de build do projeto
steps:
  - name: build
    image: node:16
    commands:
      - npm install
      - npm run build

  # Definir o passo de deploy do bot
  - name: deploy
    image: node:16
    commands:
      - npm install -g pm2
      - pm2 start build/index.js --name "phb-bot"
