---
kind: pipeline
type: docker
name: php-bot

steps:
- name: build
  image: node:18
  environment:
    BOT_TOKEN:
      from_secret: bot_token
  commands:
  - npm install
  - npm run build

- name: deploy
  image: node:18
  environment:
    BOT_TOKEN:
      from_secret: bot_token
  commands:
  - npm install -g pm2
  - pm2 start build/index.js --name "phb-bot"