---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:16
    environment:
      BOT_TOKEN:
        from_secret: BOT_TOKEN
    commands:
      - npm install
      - npm run build

  - name: deploy
    image: node:16
    environment:
      BOT_TOKEN:
        from_secret: BOT_TOKEN
    commands:
      - npm install -g pm2
      - pm2 start build/index.js --name "phb-bot"
