---
kind: pipeline
type: docker
name: phb-bot

environment:
  BOT_TOKEN:
    from_secret: BOT_TOKEN

steps:
  - name: build
    image: node:16
    commands:
    - npm install
    - npm run build

  - name: deploy
    image: node:16
    commands:
    - npm install -g pm2
    - pm2 start build/index.js --name "phb-bot"
